version: '3.8'
services:
  php:
    build: ./var/www/html
    ports:
      - "80:80"
    links:
      - db
  db:
    build: ./database/tms.sql /docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: tms
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
      
