# Use an official PHP runtime as a parent image
FROM php:5.6-apache
# Set the working directory
WORKDIR /var/www/html
# Copy the current directory contents into the container at /var/www/html
COPY . /var/www/html
# Install necessary PHP extensions
RUN docker-php-ext-install mysqli
# Port the container will listen on at runtime
EXPOSE 80